/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_ddndq_2.c
 *
 * Code generation for function 'get_ddndq_2'
 *
 */

/* Include files */
#include "get_ddndq_2.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void get_ddndq_2(const real_T q[7], const real_T o[3], real_T D_dn2[49])
{
  real_T dv[49];
  real_T a;
  real_T a_tmp;
  real_T b_a;
  real_T b_a_tmp;
  real_T b_t233_tmp;
  real_T b_t233_tmp_tmp;
  real_T b_t237_tmp;
  real_T b_t237_tmp_tmp;
  real_T b_t78_tmp;
  real_T c_a;
  real_T c_t233_tmp;
  real_T c_t237_tmp_tmp;
  real_T d_a;
  real_T d_t237_tmp_tmp;
  real_T e_a;
  real_T e_t237_tmp_tmp;
  real_T f_a;
  real_T g_a;
  real_T h_a;
  real_T t10;
  real_T t105;
  real_T t106;
  real_T t109;
  real_T t109_tmp;
  real_T t11;
  real_T t110;
  real_T t113;
  real_T t114;
  real_T t119;
  real_T t119_tmp;
  real_T t12;
  real_T t120;
  real_T t120_tmp;
  real_T t122;
  real_T t125;
  real_T t13;
  real_T t14;
  real_T t140;
  real_T t141;
  real_T t144;
  real_T t145;
  real_T t15;
  real_T t157;
  real_T t158;
  real_T t164;
  real_T t168;
  real_T t19;
  real_T t194;
  real_T t194_tmp;
  real_T t196;
  real_T t197_tmp;
  real_T t198;
  real_T t2;
  real_T t20;
  real_T t201;
  real_T t203;
  real_T t204;
  real_T t209;
  real_T t21;
  real_T t213;
  real_T t213_tmp;
  real_T t214;
  real_T t218;
  real_T t219;
  real_T t221_tmp;
  real_T t222;
  real_T t23;
  real_T t230;
  real_T t231;
  real_T t233;
  real_T t233_tmp;
  real_T t233_tmp_tmp;
  real_T t237;
  real_T t237_tmp;
  real_T t237_tmp_tmp;
  real_T t238;
  real_T t24;
  real_T t241;
  real_T t244;
  real_T t245;
  real_T t25;
  real_T t253;
  real_T t263;
  real_T t265;
  real_T t28;
  real_T t28_tmp;
  real_T t29;
  real_T t3;
  real_T t30;
  real_T t31;
  real_T t31_tmp;
  real_T t32;
  real_T t33;
  real_T t34;
  real_T t35;
  real_T t38;
  real_T t4;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t47;
  real_T t48;
  real_T t49;
  real_T t5;
  real_T t50;
  real_T t50_tmp;
  real_T t6;
  real_T t61;
  real_T t67_tmp;
  real_T t69;
  real_T t7;
  real_T t70;
  real_T t74;
  real_T t75_tmp;
  real_T t75_tmp_tmp;
  real_T t76;
  real_T t78_tmp;
  real_T t8;
  real_T t9;
  real_T t93;
  real_T t95_tmp;
  real_T t95_tmp_tmp;
  int32_T i;
  int32_T i1;
  /* GET_DDDQ_2 */
  /*     D_DN2 = GET_DDDQ_2(O1,O2,O3,Q1,Q2,Q3,Q4,Q5,Q6) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     08-Dec-2021 21:30:00 */
  t2 = muDoubleScalarCos(q[0]);
  t3 = muDoubleScalarCos(q[1]);
  t4 = muDoubleScalarCos(q[2]);
  t5 = muDoubleScalarCos(q[3]);
  t6 = muDoubleScalarCos(q[4]);
  t7 = muDoubleScalarCos(q[5]);
  t8 = muDoubleScalarSin(q[0]);
  t9 = muDoubleScalarSin(q[1]);
  t10 = muDoubleScalarSin(q[2]);
  t11 = muDoubleScalarSin(q[3]);
  t12 = muDoubleScalarSin(q[4]);
  t13 = muDoubleScalarSin(q[5]);
  t14 = o[1] * t2;
  t15 = o[0] * t8;
  t19 = t2 * t4;
  t20 = t4 * t8;
  t21 = t8 * t10;
  t23 = t3 * 0.4;
  t24 = t3 * 400.0;
  t25 = t9 * 0.4;
  t28_tmp = t8 * t9;
  t28 = t28_tmp * t11;
  t29 = t3 * 4000.0;
  t31_tmp = t2 * t3;
  t31 = t31_tmp * t10;
  t253 = t2 * t5;
  t32 = t253 * t10;
  t263 = t2 * t9;
  t34 = t263 * t11;
  t47 = t28_tmp * -0.4;
  t48 = t3 * 0.21;
  t70 = t263 * 0.21;
  t75_tmp_tmp = t3 * t4;
  t75_tmp = t75_tmp_tmp * t11;
  t78_tmp = t2 * t10;
  b_t78_tmp = t78_tmp * t11;
  t119_tmp = t253 * t9;
  t119 = t119_tmp * 0.081;
  t120_tmp = t5 * t8 * t9;
  t120 = t120_tmp * 0.081;
  t30 = t3 * t19;
  t33 = t3 * t21;
  t35 = t5 * t21;
  t38 = t2 * t25;
  t42 = t5 * t25;
  t43 = t8 * t25;
  t44 = t21 * 0.4;
  t50_tmp = t3 * t5;
  t50 = t50_tmp * t20;
  t67_tmp = t4 * t11;
  t69 = t5 * t48;
  t74 = o[0] + t263 * -0.4;
  t76 = o[1] + t47;
  t93 = t20 + t31;
  t95_tmp_tmp = t3 * t11;
  t95_tmp = t95_tmp_tmp * t20;
  t109_tmp = t11 * t21;
  t109 = t109_tmp * 0.081;
  t110 = t20 * 0.0607;
  t122 = (-o[2] + t23) + 0.34;
  t125 = t28 * 0.0607;
  t140 = t31 * 0.0607;
  t141 = t32 * 0.0607;
  t145 = t34 * 0.0607;
  t157 = (-o[2] + t48) + 0.34;
  t194_tmp = t4 * t9 * t11;
  t194 = (t3 * 40.0 + t50_tmp * 21.0) + t194_tmp * 21.0;
  t49 = t5 * t30;
  t61 = t5 * t38;
  a = muDoubleScalarAbs(t74);
  b_a = muDoubleScalarAbs(t76);
  t105 = o[0] + -t70;
  t106 = o[1] + -(t28_tmp * 0.21);
  c_a = muDoubleScalarAbs(t122);
  t144 = t33 * 0.0607;
  t158 = t78_tmp * 0.4 + t20 * t23;
  t168 = t50 * 0.0607;
  d_a = muDoubleScalarAbs(t157);
  t197_tmp = t30 * 0.4 - t44;
  t198 = (t28 + t32) + t50;
  t203 = t110 + t140;
  t209 = (t69 + t194_tmp * 0.21) + t122;
  t214 = (b_t78_tmp * 0.081 + -t120) + t95_tmp * 0.081;
  t218 = ((t76 + b_t78_tmp * 0.21) + t120_tmp * -0.21) + t11 * t20 * t48;
  t253 = t4 * t5;
  t233_tmp = t95_tmp_tmp * t12;
  t233_tmp_tmp = t6 * t9;
  b_t233_tmp = t233_tmp_tmp * t10;
  b_t233_tmp_tmp = t253 * t9;
  c_t233_tmp = b_t233_tmp_tmp * t12;
  t233 = ((((t29 + t5 * t29) + t233_tmp * 607.0) + t194_tmp * 4000.0) +
          -(b_t233_tmp * 607.0)) +
         -(c_t233_tmp * 607.0);
  t28_tmp = t50_tmp * t7;
  t237_tmp = t4 * t7 * t9 * t11;
  t237_tmp_tmp = t3 * t6;
  b_t237_tmp_tmp = t237_tmp_tmp * t11;
  t230 = b_t237_tmp_tmp * t13;
  c_t237_tmp_tmp = t9 * t10;
  d_t237_tmp_tmp = c_t237_tmp_tmp * t12;
  b_t237_tmp = d_t237_tmp_tmp * t13;
  e_t237_tmp_tmp = t253 * t6 * t9;
  t253 = e_t237_tmp_tmp * t13;
  t237 = ((((((t24 + t5 * t24) + t28_tmp * 81.0) + t194_tmp * 400.0) +
            t237_tmp * 81.0) +
           t230 * 81.0) +
          b_t237_tmp * 81.0) +
         -(t253 * 81.0);
  t263 = t5 * t23 + t67_tmp * t25;
  t238 = (((t263 + t122) + t233_tmp * 0.0607) + -(b_t233_tmp * 0.0607)) +
         -(c_t233_tmp * 0.0607);
  t241 =
      (((((t263 + t28_tmp * 0.081) + t122) + t237_tmp * 0.081) + t230 * 0.081) +
       b_t237_tmp * 0.081) +
      -(t253 * 0.081);
  b_t237_tmp = muDoubleScalarAbs(t105);
  e_a = muDoubleScalarAbs(t106);
  t113 = t19 + -t33;
  t114 = t21 + -t30;
  t164 = t49 * 0.0607;
  t196 = t11 * (t20 * 0.4 + t78_tmp * t23);
  t201 = (t34 + t49) + -t35;
  f_a = muDoubleScalarAbs(t209);
  t219 = (t125 + t141) + t168;
  g_a = muDoubleScalarAbs(t218);
  h_a = muDoubleScalarAbs(t238);
  t265 = muDoubleScalarAbs(t241);
  t204 = t19 * 0.0607 + -t144;
  t213_tmp = t11 * t30;
  t213 = (t109 + t119) + -(t213_tmp * 0.081);
  t221_tmp = -o[0] + t38;
  t70 = ((t221_tmp + t109_tmp * 0.21) + t5 * t70) + -(t213_tmp * 0.21);
  t222 = (t145 + -(t35 * 0.0607)) + t164;
  t38 = 1.0 / muDoubleScalarSqrt((a * a + b_a * b_a) + c_a * c_a);
  a = muDoubleScalarAbs(t70);
  t231 = t12 * t113 * 0.081 + t6 * t198 * 0.081;
  t263 = (((-o[1] + t43) + t8 * t42) + b_t78_tmp * -0.4) + t95_tmp * -0.4;
  b_a = muDoubleScalarAbs(
      ((((t263 + t6 * t19 * -0.0607) + t6 * t144) + t12 * t141) + t12 * t125) +
      t12 * t168);
  t253 = t12 * t13;
  a_tmp = t6 * t13;
  t237_tmp = ((t221_tmp + t11 * t44) + t61) + t11 * (t30 * -0.4);
  b_a_tmp = t7 * t11;
  c_a = muDoubleScalarAbs(
      (((((((t237_tmp + t7 * t119) + t7 * t109) + -(t253 * t20 * 0.081)) +
          a_tmp * t34 * 0.081) +
         b_a_tmp * t30 * -0.081) +
        -(t253 * t31 * 0.081)) +
       -(a_tmp * t35 * 0.081)) +
      a_tmp * t49 * 0.081);
  t28_tmp = muDoubleScalarAbs((((((((t263 + t7 * t120) + t253 * t19 * 0.081) +
                                   t2 * t7 * t10 * t11 * -0.081) +
                                  a_tmp * t32 * 0.081) +
                                 a_tmp * t28 * 0.081) +
                                t3 * t7 * t11 * t20 * -0.081) +
                               -(t253 * t33 * 0.081)) +
                              a_tmp * t50 * 0.081);
  t230 = 1.0 /
         muDoubleScalarSqrt((b_t237_tmp * b_t237_tmp + e_a * e_a) + d_a * d_a);
  t263 = (t76 + t5 * t47) + t11 * t158;
  t244 = (t263 + t6 * t204) + -(t12 * t219);
  t253 = (t221_tmp + t61) + -t11 * t197_tmp;
  t245 = (t253 + t6 * t203) + t12 * t222;
  d_a = muDoubleScalarAbs(((((t237_tmp + t6 * t110) + t6 * t140) + t12 * t145) +
                           t12 * t35 * -0.0607) +
                          t12 * t164);
  t140 = t12 * t93 * 0.081 - t6 * t201 * 0.081;
  t61 = (t253 + t7 * t213) + -t13 * t140;
  t253 = 1.0 / muDoubleScalarSqrt((f_a * f_a + g_a * g_a) + a * a);
  t47 = (t263 + t7 * t214) + -(t13 * t231);
  t265 =
      1.0 / muDoubleScalarSqrt((t265 * t265 + c_a * c_a) + t28_tmp * t28_tmp);
  t263 = 1.0 / muDoubleScalarSqrt((h_a * h_a + d_a * d_a) + b_a * b_a);
  memset(&dv[0], 0, 14U * sizeof(real_T));
  t119 = t9 * (t14 + -t15);
  dv[14] = t119 * t230 * -0.21;
  t120 = t3 * t8;
  dv[15] = t230 *
           ((t9 * t157 * 21.0 + t31_tmp * t105 * 21.0) + t120 * t106 * 21.0) *
           -0.01;
  dv[16] = 0.0;
  dv[17] = 0.0;
  dv[18] = 0.0;
  dv[19] = 0.0;
  dv[20] = 0.0;
  dv[21] = t119 * t38 * -0.4;
  dv[22] =
      t38 * ((t9 * t122 * 2.0 + t31_tmp * t74 * 2.0) + t120 * t76 * 2.0) * -0.2;
  dv[23] = 0.0;
  dv[24] = 0.0;
  dv[25] = 0.0;
  dv[26] = 0.0;
  dv[27] = 0.0;
  t119 = t5 * t9;
  t120 = t9 * t14;
  t125 = t9 * t15;
  t141 = o[1] * t11 * t21;
  t164 = t119 * t14;
  t44 = t119 * t15;
  t109 = o[0] * t2;
  f_a = t109 * t10 * t11;
  g_a = t75_tmp * t14;
  dv[28] = t253 *
           (((((((t120 * 40.0 - t125 * 40.0) + t141 * 21.0) + t164 * 21.0) -
               t44 * 21.0) +
              f_a * 21.0) -
             g_a * 21.0) +
            t75_tmp * t15 * 21.0) *
           -0.01;
  dv[29] = t253 *
           ((t209 * ((t25 + t119 * 0.21) - t75_tmp * 0.21) * 2.0 -
             t2 * t194 * t70 / 50.0) +
            t8 * t194 * t218 / 50.0) *
           -0.5;
  dv[30] = t253 *
           ((t11 * t218 * (t19 * 0.21 - t33 * 0.21) * 2.0 +
             t11 * t70 * (t20 * 0.21 + t31 * 0.21) * 2.0) -
            c_t237_tmp_tmp * t11 * t209 * 0.42) /
           2.0;
  dv[31] = t253 *
           ((t218 * ((t28 * 0.21 + t32 * 0.21) + t20 * t69) * -2.0 +
             t209 * (t11 * t48 - b_t233_tmp_tmp * 0.21) * 2.0) +
            t70 * ((t34 * 0.21 - t35 * 0.21) + t49 * 0.21) * 2.0) *
           -0.5;
  dv[32] = 0.0;
  dv[33] = 0.0;
  dv[34] = 0.0;
  t119 = t237_tmp_tmp * t10;
  b_t237_tmp = t9 * t11 * t12;
  t38 = t75_tmp_tmp * t5;
  t70 = t38 * t12;
  e_a = o[0] * t12;
  t144 = o[1] * t12;
  t168 = o[0] * t6;
  t221_tmp = o[1] * t6;
  t230 = t67_tmp * t15;
  dv[35] =
      t263 *
      (((((((((((((((((t120 * 4000.0 - t125 * 4000.0) + t168 * t19 * 607.0) +
                     t221_tmp * t20 * 607.0) +
                    t141 * 4000.0) -
                   e_a * t32 * 607.0) -
                  t144 * t35 * 607.0) +
                 t164 * 4000.0) -
                t44 * 4000.0) +
               f_a * 4000.0) -
              g_a * 4000.0) +
             t119 * t14 * 607.0) -
            t119 * t15 * 607.0) +
           b_t237_tmp * t14 * 607.0) -
          b_t237_tmp * t15 * 607.0) +
         t230 * t29) +
        t70 * t14 * 607.0) -
       t70 * t15 * 607.0) *
      -0.0001;
  t237_tmp = (t25 + t42) + t75_tmp * -0.4;
  dv[36] = t263 *
           ((t238 *
                 (((t237_tmp + t119 * 0.0607) + b_t237_tmp * 0.0607) +
                  t70 * 0.0607) *
                 2.0 -
             t2 * t233 * t245 / 5000.0) +
            t8 * t233 * t244 / 5000.0) *
           -0.5;
  t119 = t5 * t12;
  b_t237_tmp = t10 * t11;
  dv[37] =
      t263 *
      ((t245 *
            ((-t196 + t6 * (t21 * 0.0607 - t30 * 0.0607)) +
             t119 * t93 * 0.0607) *
            2.0 +
        t244 *
            ((t11 * t113 * -0.4 + t6 * (t78_tmp * 0.0607 + t3 * t110)) +
             t119 * t113 * 0.0607) *
            2.0) +
       t9 * t238 *
           ((t4 * t6 * 607.0 + b_t237_tmp * 4000.0) - t5 * t10 * t12 * 607.0) /
           5000.0) *
      -0.5;
  t119 = t11 * t43 + t5 * t158;
  dv[38] = t263 *
           ((t245 *
                 ((t34 * 0.4 - t12 * ((t109_tmp * 0.0607 - t213_tmp * 0.0607) +
                                      t119_tmp * 0.0607)) +
                  t5 * t197_tmp) *
                 -2.0 +
             t244 *
                 (t119 + t12 * ((t120_tmp * -0.0607 + b_t78_tmp * 0.0607) +
                                t95_tmp_tmp * t110)) *
                 2.0) +
            t238 *
                (((t4 * t42 - t95_tmp_tmp * 0.4) + t50_tmp * t12 * 0.0607) +
                 t194_tmp * t12 * 0.0607) *
                2.0) /
           2.0;
  dv[39] = t263 *
           ((t244 * (t12 * t204 + t6 * t219) * 2.0 +
             t245 * (t12 * t203 - t6 * t222) * 2.0) -
            t238 *
                ((b_t237_tmp_tmp * 0.0607 + d_t237_tmp_tmp * 0.0607) -
                 e_t237_tmp_tmp * 0.0607) *
                2.0) *
           -0.5;
  dv[40] = 0.0;
  dv[41] = 0.0;
  t70 = t5 * t7 * t9;
  t263 = t75_tmp_tmp * t7 * t11;
  t28_tmp = t3 * t10 * t12 * t13;
  t253 = t233_tmp_tmp * t11 * t13;
  t38 = t38 * t6 * t13;
  dv[42] = t265 *
           (((((((((((((((((((((((t120 * 400.0 - t125 * 400.0) + t141 * 400.0) +
                                t164 * 400.0) -
                               t44 * 400.0) +
                              f_a * 400.0) +
                             o[1] * t7 * t11 * t21 * 81.0) -
                            e_a * t13 * t19 * 81.0) -
                           t144 * t13 * t20 * 81.0) -
                          t168 * t13 * t32 * 81.0) -
                         t221_tmp * t13 * t35 * 81.0) -
                        g_a * 400.0) +
                       t70 * t14 * 81.0) -
                      t70 * t15 * 81.0) +
                     t230 * t24) +
                    t109 * t7 * t10 * t11 * 81.0) -
                   t263 * t14 * 81.0) +
                  t263 * t15 * 81.0) -
                 t28_tmp * t14 * 81.0) +
                t28_tmp * t15 * 81.0) +
               t253 * t14 * 81.0) -
              t253 * t15 * 81.0) +
             t38 * t14 * 81.0) +
            t38 * t15 * -81.0) *
           -0.001;
  dv[43] =
      t265 *
      ((t241 *
            (((((t237_tmp + t70 * 0.081) - t263 * 0.081) - t28_tmp * 0.081) +
              t253 * 0.081) +
             t38 * 0.081) *
            2.0 -
        t2 * t237 * t61 / 500.0) +
       t8 * t237 * t47 / 500.0) *
      -0.5;
  t120 = t5 * t6;
  dv[44] =
      t265 *
      ((t47 *
            ((t13 * (t12 * (t78_tmp + t3 * t20) * 0.081 - t120 * t113 * 0.081) +
              t11 * (t19 * 0.4 - t33 * 0.4)) +
             b_a_tmp * t113 * 0.081) *
            2.0 +
        t61 *
            ((t196 + t13 * (t12 * t114 * 0.081 - t120 * t93 * 0.081)) +
             b_a_tmp * t93 * 0.081) *
            2.0) -
       t9 * t241 *
           (((b_t237_tmp * 400.0 + t7 * t10 * t11 * 81.0) -
             t4 * t12 * t13 * 81.0) -
            t120 * t10 * t13 * 81.0) /
           500.0) /
      2.0;
  dv[45] = t265 *
           ((t241 *
                 (((t11 * t23 +
                    t7 * (t95_tmp_tmp * 0.081 - b_t233_tmp_tmp * 0.081)) -
                   a_tmp * (t50_tmp + t194_tmp) * 0.081) -
                  b_t233_tmp_tmp * 0.4) *
                 2.0 -
             t47 *
                 ((t119 + t7 * ((t28 * 0.081 + t32 * 0.081) + t50 * 0.081)) +
                  a_tmp * ((-t5 * t8 * t9 + b_t78_tmp) + t95_tmp) * 0.081) *
                 2.0) +
            t61 *
                (((t34 * 0.4 - t5 * t114 * 0.4) +
                  t7 * ((t34 * 0.081 - t35 * 0.081) + t49 * 0.081)) -
                 a_tmp * ((t109_tmp + t11 * -t30) + t119_tmp) * 0.081) *
                2.0) *
           -0.5;
  dv[46] = t265 *
           ((t13 * t61 * (t6 * t93 * 0.081 + t12 * t201 * 0.081) * 2.0 +
             t13 * t47 * (t6 * t113 * 0.081 - t12 * t198 * 0.081) * 2.0) -
            t13 * t241 *
                ((b_t233_tmp * 0.081 - t233_tmp * 0.081) + c_t233_tmp * 0.081) *
                2.0) *
           -0.5;
  dv[47] = t265 *
           ((t241 *
                 (t13 * (t50_tmp * 0.081 + t194_tmp * 0.081) -
                  t7 * ((b_t237_tmp_tmp * 0.081 + d_t237_tmp_tmp * 0.081) -
                        e_t237_tmp_tmp * 0.081)) *
                 2.0 +
             t47 * (t13 * t214 + t7 * t231) * 2.0) +
            t61 * (t13 * t213 + t7 * t140) * 2.0) *
           -0.5;
  dv[48] = 0.0;
  for (i = 0; i < 7; i++) {
    for (i1 = 0; i1 < 7; i1++) {
      D_dn2[i1 + 7 * i] = dv[i + 7 * i1];
    }
  }
}

/* End of code generation (get_ddndq_2.c) */
