/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_dn_3.c
 *
 * Code generation for function 'get_dn_3'
 *
 */

/* Include files */
#include "get_dn_3.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Function Definitions */
void get_dn_3(const real_T q[7], const real_T o[3], real_T dn3[7])
{
  real_T a;
  real_T a_tmp;
  real_T b_a;
  real_T c_a;
  real_T d_a;
  real_T t10;
  real_T t103;
  real_T t11;
  real_T t118;
  real_T t12;
  real_T t129;
  real_T t13;
  real_T t130;
  real_T t131;
  real_T t132;
  real_T t15;
  real_T t153;
  real_T t155;
  real_T t162;
  real_T t17;
  real_T t174;
  real_T t175;
  real_T t178;
  real_T t179;
  real_T t181;
  real_T t182;
  real_T t184;
  real_T t188;
  real_T t2;
  real_T t20;
  real_T t202;
  real_T t203;
  real_T t21;
  real_T t214;
  real_T t22;
  real_T t220;
  real_T t227;
  real_T t229_tmp;
  real_T t23;
  real_T t232;
  real_T t233;
  real_T t24;
  real_T t242;
  real_T t243;
  real_T t245;
  real_T t25;
  real_T t254;
  real_T t26;
  real_T t262;
  real_T t269;
  real_T t28;
  real_T t29;
  real_T t3;
  real_T t30;
  real_T t31;
  real_T t314;
  real_T t324;
  real_T t325;
  real_T t33;
  real_T t332;
  real_T t332_tmp;
  real_T t335;
  real_T t34;
  real_T t340;
  real_T t342;
  real_T t343;
  real_T t344;
  real_T t35;
  real_T t36;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t4;
  real_T t40;
  real_T t41;
  real_T t41_tmp;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t45;
  real_T t5;
  real_T t52;
  real_T t57;
  real_T t58;
  real_T t59;
  real_T t6;
  real_T t60;
  real_T t61;
  real_T t7;
  real_T t77;
  real_T t8;
  real_T t9;
  /* GET_D_3 */
  /*     DN3 = GET_D_3(O1,O2,O3,Q1,Q2,Q3,Q4,Q5,Q6) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     08-Dec-2021 21:29:48 */
  t2 = muDoubleScalarCos(q[0]);
  t3 = muDoubleScalarCos(q[1]);
  t4 = muDoubleScalarCos(q[2]);
  t5 = muDoubleScalarCos(q[3]);
  t6 = muDoubleScalarCos(q[4]);
  t7 = muDoubleScalarCos(q[5]);
  t8 = muDoubleScalarSin(q[0]);
  t9 = muDoubleScalarSin(q[1]);
  t10 = muDoubleScalarSin(q[2]);
  t11 = muDoubleScalarSin(q[3]);
  t12 = muDoubleScalarSin(q[4]);
  t13 = muDoubleScalarSin(q[5]);
  t20 = o[2] * 50.0;
  t15 = t3 * t3;
  t17 = t9 * t9;
  t21 = t2 * t4;
  t22 = t3 * t5;
  t23 = t2 * t10;
  t24 = t4 * t8;
  t25 = t3 * t11;
  t26 = t8 * t10;
  t28 = t3 * 0.4;
  t214 = t8 * t9;
  t29 = t214 * t11;
  t31 = t9 * t10 * t12;
  t36 = t2 * t5 * t9;
  t38 = t4 * t5 * t9;
  t41_tmp = t2 * t9;
  t41 = t41_tmp * t11;
  t42 = t5 * t8 * t9;
  t45 = t4 * t9 * t11;
  t52 = t214 * 0.4;
  t10 *= t6 * t9;
  t181 = t10 * 0.0607;
  t30 = t11 * t26;
  t33 = t3 * t21;
  t34 = t3 * t23;
  t35 = t3 * t24;
  t37 = t5 * t23;
  t39 = t6 * t25;
  t40 = t3 * t26;
  t43 = t11 * t23;
  t44 = t5 * t26;
  t57 = t21 * t22;
  t58 = t21 * t25;
  t59 = t22 * t24;
  t60 = t6 * t38;
  t61 = t24 * t25;
  t77 = t42 * 0.4;
  t118 = t42 * 0.21;
  t129 = t24 * 0.0607;
  t130 = t25 * 0.0607;
  t162 = t29 * 0.0607;
  t179 = t41 * 0.0607;
  t245 = t12 * t38;
  t214 = t245 * -0.0607;
  t4 = t23 + t35;
  t103 = t24 + t34;
  t174 = t34 * 0.0607;
  t175 = t37 * 0.0607;
  t178 = t40 * 0.0607;
  t182 = t12 * t130;
  t202 = t57 * 0.0607;
  t203 = t59 * 0.0607;
  t227 = (t29 + t37) + t59;
  t232 = t22 * 0.21 + t45 * 0.21;
  t131 = t21 + -t40;
  t132 = t26 + -t33;
  t153 = t5 * t4;
  t155 = t12 * t103;
  t220 = t11 * (t23 * 0.4 + t24 * t28);
  t229_tmp = t11 * t4;
  t233 = (t41 + t57) + -t44;
  t242 = t6 * t227;
  t243 = t232 * t232;
  t254 = t7 * (t22 * 0.081 + t45 * 0.081);
  t4 = -o[2] + t28;
  t269 = (t4 + t232) + 0.34;
  a = (((t22 * 1900.0 + t12 * t25 * 607.0) + t45 * 1900.0) + -(t10 * 607.0)) +
      -(t245 * 607.0);
  t325 = (((t22 * 0.19 + t45 * 0.19) + t182) + -t181) + t214;
  t332_tmp = (t4 + t22 * 0.4) + t45 * 0.4;
  t332 = (((t332_tmp + t182) + -t181) + t214) + 0.34;
  t184 = t5 * t132;
  t188 = t12 * t131;
  t245 = t11 * (t23 * 0.21 + t35 * 0.21);
  t35 = t6 * t233;
  t262 = t6 * (t129 + t174);
  a_tmp = o[0] * t2;
  b_a = muDoubleScalarAbs(
      ((((-t20 + t15 * t20) + -(t15 * 17.0)) + a_tmp * t3 * t9 * 50.0) +
       o[1] * t3 * t8 * t9 * 50.0) +
      17.0);
  c_a = muDoubleScalarAbs((((o[0] * t15 * 50.0 + t2 * t3 * t9 * 17.0) +
                            o[2] * t2 * t3 * t9 * -50.0) +
                           o[0] * (t8 * t8) * t17 * 50.0) +
                          -(o[1] * t2 * t8 * t17 * 50.0));
  d_a = muDoubleScalarAbs((((o[1] * t15 * 50.0 + t3 * t8 * t9 * 17.0) +
                            o[2] * t3 * t8 * t9 * -50.0) +
                           o[1] * (t2 * t2) * t17 * 50.0) +
                          -(a_tmp * t8 * t17 * 50.0));
  t314 = a * a;
  t4 = t7 * t22;
  t10 = t7 * t45;
  t214 = t13 * t39;
  t8 = t13 * t31;
  t182 = t13 * t60;
  t324 = (((t4 * 0.045 + t10 * 0.045) + t214 * 0.045) + t8 * 0.045) +
         -(t182 * 0.045);
  t335 =
      (((((t332_tmp + t4 * 0.126) + t10 * 0.126) + t214 * 0.126) + t8 * 0.126) +
       -(t182 * 0.126)) +
      0.34;
  t4 = t6 * t13;
  t10 = t12 * t13;
  t340 = ((((((t7 * t42 * 0.045 + t10 * t21 * 0.045) + -(t7 * t43 * 0.045)) +
             t4 * t37 * 0.045) +
            t4 * t29 * 0.045) +
           -(t7 * t61 * 0.045)) +
          -(t10 * t40 * 0.045)) +
         t4 * t59 * 0.045;
  t342 = ((((((t7 * t36 * 0.045 + t7 * t30 * 0.045) + -(t10 * t24 * 0.045)) +
             t4 * t41 * 0.045) +
            -(t7 * t58 * 0.045)) +
           -(t10 * t34 * 0.045)) +
          -(t4 * t44 * 0.045)) +
         t4 * t57 * 0.045;
  t343 = ((((((t30 * 0.19 + t36 * 0.19) + -(t58 * 0.19)) + t6 * t129) +
            t6 * t174) +
           t12 * t179) +
          t12 * t44 * -0.0607) +
         t12 * t202;
  t344 =
      ((((((t42 * 0.19 + -(t43 * 0.19)) + -(t61 * 0.19)) + t6 * t21 * -0.0607) +
         t6 * t178) +
        t12 * t175) +
       t12 * t162) +
      t12 * t203;
  t182 = t6 * (t21 * 0.0607 + -t178);
  t10 = t13 * (t31 * 0.081 + t6 * (t25 + -t38) * 0.081);
  a_tmp = t118 - t245;
  t25 = a_tmp * a_tmp;
  a = t7 * (t22 + t45) + t13 * ((t31 + t39) + -t60);
  t132 *= t11;
  t57 =
      ((t36 * 1900.0 + t6 * t103 * 607.0) + t132 * 1900.0) + t12 * t233 * 607.0;
  t39 = t36 * 0.21 + t11 * (t26 * 0.21 + -(t33 * 0.21));
  t28 = t7 * (t36 * 0.081 + t132 * 0.081);
  t60 = a * a;
  t4 = o[1] + -t52;
  t178 = t4 + (-t118 + t245);
  a = t7 * ((t30 + t36) + -t58) + -t13 * (t155 - t35);
  t24 = ((t42 * 1900.0 + -(t229_tmp * 1900.0)) + -(t6 * t131 * 607.0)) +
        t12 * t227 * 607.0;
  t21 = t57 * t57;
  t174 = ((t332_tmp + t254) + t10) + 0.34;
  t57 = ((t181 + t254) + -(t12 * (t130 + -(t38 * 0.0607)))) + t10;
  t23 = (t4 + -t77) + t220;
  t129 = (t23 + t182) + -(t12 * ((t162 + t175) + t203));
  t4 = -o[0] + t41_tmp * 0.4;
  t214 = (t4 + t36 * 0.4) + -t11 * (t33 * 0.4 - t26 * 0.4);
  t34 = (t214 + t262) + t12 * ((t179 + -(t44 * 0.0607)) + t202);
  t17 = t39 * t39;
  t37 = t4 + t39;
  t245 = t13 * (t188 * 0.081 + t6 * (t29 + t153) * 0.081);
  t10 = t13 * (t155 * 0.081 + t6 * (t41 - t184) * -0.081);
  t59 = a * a;
  t40 = t24 * t24;
  t3 = t57 * t57;
  t9 = (t214 + t7 * ((t30 * 0.126 + t36 * 0.126) + -(t58 * 0.126))) +
       -t13 * (t155 * 0.126 - t35 * 0.126);
  a = t7 * ((t43 + t61) + -t42) + -(t13 * (t188 + t242));
  t15 = muDoubleScalarSqrt((b_a * b_a + c_a * c_a) + d_a * d_a) / 50.0;
  t4 = t7 * (t42 * 0.081 - t229_tmp * 0.081);
  t132 = ((t182 - t12 * (t162 + t153 * 0.0607)) + t245) + t4;
  t5 = t132 * t132;
  t8 = ((t262 - t28) + t10) + t12 * (t179 - t184 * 0.0607);
  t182 = t8 * t8;
  t2 = a * a;
  t20 = 1.0 / ((t243 + t17) + t25);
  t23 = (t23 + t7 * ((t43 * 0.126 + -(t42 * 0.126)) + t61 * 0.126)) +
        -(t13 * (t188 * 0.126 + t242 * 0.126));
  t214 = (t214 + t28) + -t10;
  t28 = 1.0 / ((t314 + t21) + t40);
  t10 = 1.0 / ((t3 + t5) + t182);
  t35 = 1.0 / ((t60 + t59) + t2);
  t4 += (((-o[1] + t52) + t77) - t220) + t245;
  a = muDoubleScalarAbs((t174 * (t3 * t10 - 1.0) - t57 * t214 * t10 * t8) +
                        t57 * t10 * t132 * t4);
  t3 = t174 * t57 * t10;
  b_a = muDoubleScalarAbs((-(t5 * t10 - 1.0) * t4 - t3 * t132) +
                          t214 * t10 * t132 * t8);
  c_a = muDoubleScalarAbs((t214 * (t182 * t10 - 1.0) - t3 * t8) -
                          t10 * t132 * t8 * t4);
  d_a = muDoubleScalarAbs(o[0]);
  t57 = muDoubleScalarAbs(o[1]);
  t24 = muDoubleScalarAbs((t269 * (t243 * t20 - 1.0) + t232 * t39 * t37 * t20) -
                          t232 * t178 * t20 * a_tmp);
  t132 = t232 * t269;
  t245 = muDoubleScalarAbs((t37 * (t17 * t20 - 1.0) + t132 * t39 * t20) -
                           t39 * t178 * t20 * a_tmp);
  t5 = muDoubleScalarAbs((t178 * (t25 * t20 - 1.0) - t132 * t20 * a_tmp) -
                         t39 * t37 * t20 * a_tmp);
  t182 = muDoubleScalarAbs(
      (t332 * (t314 * t28 - 1.0) + t325 * t343 * t34 * t28 * 1.0E+8) -
      t325 * t344 * t129 * t28 * 1.0E+8);
  a_tmp = t325 * t332;
  t132 = t343 * t344;
  t8 = muDoubleScalarAbs(
      (t34 * (t21 * t28 - 1.0) + a_tmp * t343 * t28 * 1.0E+8) -
      t132 * t129 * t28 * 1.0E+8);
  t3 = muDoubleScalarAbs(
      (-t129 * (t40 * t28 - 1.0) + a_tmp * t344 * t28 * 1.0E+8) +
      t132 * t34 * t28 * 1.0E+8);
  t10 = muDoubleScalarAbs((t335 * (t60 * t35 - 1.0) -
                           t324 * t340 * t23 * t35 * 493.82716049382719) +
                          t324 * t342 * t9 * t35 * 493.82716049382719);
  a_tmp = t324 * t335;
  t132 = t340 * t342;
  t214 = muDoubleScalarAbs(
      (t9 * (t59 * t35 - 1.0) + a_tmp * t342 * t35 * 493.82716049382719) -
      t132 * t23 * t35 * 493.82716049382719);
  t4 = muDoubleScalarAbs(
      (-t23 * (t2 * t35 - 1.0) + a_tmp * t340 * t35 * 493.82716049382719) +
      t132 * t9 * t35 * 493.82716049382719);
  dn3[0] = muDoubleScalarSqrt(d_a * d_a + t57 * t57);
  dn3[1] = t15;
  dn3[2] = t15;
  dn3[3] = muDoubleScalarSqrt((t24 * t24 + t245 * t245) + t5 * t5);
  dn3[4] = muDoubleScalarSqrt((t182 * t182 + t8 * t8) + t3 * t3);
  dn3[5] = muDoubleScalarSqrt((a * a + b_a * b_a) + c_a * c_a);
  dn3[6] = muDoubleScalarSqrt((t10 * t10 + t214 * t214) + t4 * t4);
}

/* End of code generation (get_dn_3.c) */
