/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_dn_2.c
 *
 * Code generation for function 'get_dn_2'
 *
 */

/* Include files */
#include "get_dn_2.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Function Definitions */
void get_dn_2(const real_T q[7], const real_T o[21], real_T dn2[7])
{
  real_T a;
  real_T a_tmp;
  real_T b_a;
  real_T b_a_tmp;
  real_T c_a;
  real_T c_a_tmp;
  real_T d_a;
  real_T d_a_tmp;
  real_T e_a;
  real_T e_a_tmp;
  real_T f_a;
  real_T f_a_tmp;
  real_T g_a;
  real_T g_a_tmp;
  real_T h_a;
  real_T h_a_tmp;
  real_T i_a;
  real_T i_a_tmp;
  real_T j_a_tmp;
  real_T k_a_tmp;
  real_T l_a_tmp;
  real_T m_a_tmp;
  real_T n_a_tmp;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t26;
  real_T t26_tmp;
  real_T t30_tmp;
  real_T t36_tmp;
  real_T t38_tmp;
  real_T t39;
  real_T t4;
  real_T t40;
  real_T t43_tmp;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  /* GET_D_2 */
  /*     DN2 = GET_D_2(O1,O2,O3,Q1,Q2,Q3,Q4,Q5,Q6) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     08-Dec-2021 21:29:45 */
  a = muDoubleScalarAbs(o[0]);
  b_a = muDoubleScalarAbs(o[1]);
  t4 = muDoubleScalarCos(q[0]);
  t5 = muDoubleScalarCos(q[1]);
  t6 = muDoubleScalarCos(q[2]);
  t7 = muDoubleScalarCos(q[3]);
  t8 = muDoubleScalarCos(q[4]);
  t9 = muDoubleScalarCos(q[5]);
  t10 = muDoubleScalarSin(q[0]);
  t11 = muDoubleScalarSin(q[1]);
  t12 = muDoubleScalarSin(q[2]);
  t13 = muDoubleScalarSin(q[3]);
  t14 = muDoubleScalarSin(q[4]);
  t15 = muDoubleScalarSin(q[5]);
  t20 = t4 * t12;
  t21 = t10 * t12;
  t22 = t5 * 0.4;
  t23 = t4 * t5 * t6;
  t24 = t5 * t6 * t10;
  t26_tmp = t4 * t11;
  t26 = t26_tmp * 0.4;
  t36_tmp = t6 * t11 * t13;
  t38_tmp = t7 * t10 * t11;
  t30_tmp = t10 * t11;
  t39 = t20 + t24;
  t40 = t21 + -t23;
  t43_tmp = t6 * t10;
  a_tmp = -o[2] + t22;
  b_a_tmp = t5 * t7;
  c_a_tmp = t5 * t13;
  d_a_tmp = t6 * t7 * t11;
  e_a_tmp = (a_tmp + t7 * t22) + t36_tmp * 0.4;
  c_a = muDoubleScalarAbs(((e_a_tmp + t15 * (t8 * (c_a_tmp - d_a_tmp) * 0.081 +
                                             t11 * t12 * t14 * 0.081)) +
                           t9 * (b_a_tmp * 0.081 + t36_tmp * 0.081)) +
                          0.34);
  f_a_tmp = o[1] + -(t30_tmp * 0.4);
  g_a_tmp = t7 * t39;
  h_a_tmp = t30_tmp * t13;
  i_a_tmp = (f_a_tmp + t38_tmp * -0.4) + t13 * (t20 * 0.4 + t43_tmp * t22);
  t6 *= t4;
  j_a_tmp = t5 * t21;
  d_a = muDoubleScalarAbs((i_a_tmp - t15 * (t8 * (g_a_tmp + h_a_tmp) * 0.081 +
                                            t14 * (t6 - j_a_tmp) * 0.081)) +
                          t9 * (t13 * t39 * 0.081 - t38_tmp * 0.081));
  t22 = -o[0] + t26;
  t10 = t4 * t7 * t11;
  k_a_tmp = t7 * t40;
  l_a_tmp = t26_tmp * t13;
  m_a_tmp = (t22 + t7 * t26) + -t13 * (t23 * 0.4 - t21 * 0.4);
  n_a_tmp = t5 * t20;
  e_a =
      muDoubleScalarAbs((m_a_tmp - t15 * (t8 * (k_a_tmp - l_a_tmp) * 0.081 +
                                          t14 * (t43_tmp + n_a_tmp) * 0.081)) +
                        t9 * (t13 * t40 * 0.081 + t10 * 0.081));
  f_a = muDoubleScalarAbs(o[2] - 0.15);
  g_a = muDoubleScalarAbs(o[2] - 0.34);
  h_a = muDoubleScalarAbs((t5 * 0.21 + -o[2]) + 0.34);
  i_a = muDoubleScalarAbs(o[0] - t26_tmp * 0.21);
  t40 = muDoubleScalarAbs(o[1] - t30_tmp * 0.21);
  t5 = muDoubleScalarAbs(f_a_tmp);
  t26_tmp = muDoubleScalarAbs(a_tmp + 0.34);
  t15 = muDoubleScalarAbs(o[0] - t26);
  t9 = muDoubleScalarAbs(((a_tmp + b_a_tmp * 0.21) + t36_tmp * 0.21) + 0.34);
  t7 = muDoubleScalarAbs((f_a_tmp + t13 * (t20 * 0.21 + t24 * 0.21)) -
                         t38_tmp * 0.21);
  t4 = muDoubleScalarAbs((t22 + t13 * (t21 * 0.21 - t23 * 0.21)) + t10 * 0.21);
  t39 = muDoubleScalarAbs(
      ((e_a_tmp + t14 * (c_a_tmp * 0.0607 - d_a_tmp * 0.0607)) -
       t8 * t11 * t12 * 0.0607) +
      0.34);
  t6 = muDoubleScalarAbs(
      (i_a_tmp - t14 * (g_a_tmp * 0.0607 + h_a_tmp * 0.0607)) +
      t8 * (t6 * 0.0607 - j_a_tmp * 0.0607));
  t22 = muDoubleScalarAbs(
      (m_a_tmp - t14 * (k_a_tmp * 0.0607 - l_a_tmp * 0.0607)) +
      t8 * (t43_tmp * 0.0607 + n_a_tmp * 0.0607));
  t10 = a * a + b_a * b_a;
  dn2[0] = muDoubleScalarSqrt(t10 + f_a * f_a);
  dn2[1] = muDoubleScalarSqrt(t10 + g_a * g_a);
  dn2[2] = muDoubleScalarSqrt((h_a * h_a + i_a * i_a) + t40 * t40);
  dn2[3] = muDoubleScalarSqrt((t5 * t5 + t26_tmp * t26_tmp) + t15 * t15);
  dn2[4] = muDoubleScalarSqrt((t9 * t9 + t7 * t7) + t4 * t4);
  dn2[5] = muDoubleScalarSqrt((t39 * t39 + t6 * t6) + t22 * t22);
  dn2[6] = muDoubleScalarSqrt((c_a * c_a + d_a * d_a) + e_a * e_a);
}

/* End of code generation (get_dn_2.c) */
