/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_dn_3.c
 *
 * Code generation for function 'get_dn_3'
 *
 */

/* Include files */
#include "get_dn_3.h"
#include "collisionFcn_U_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Variable Definitions */
static emlrtRSInfo lb_emlrtRSI = {
    359,                                                       /* lineNo */
    "get_dn_3",                                                /* fcnName */
    "G:\\My Drive\\AEROSP 740\\project\\utilities\\get_dn_3.m" /* pathName */
};

static emlrtRSInfo rb_emlrtRSI = {
    383,                                                       /* lineNo */
    "get_dn_3",                                                /* fcnName */
    "G:\\My Drive\\AEROSP 740\\project\\utilities\\get_dn_3.m" /* pathName */
};

static emlrtRSInfo sb_emlrtRSI = {
    384,                                                       /* lineNo */
    "get_dn_3",                                                /* fcnName */
    "G:\\My Drive\\AEROSP 740\\project\\utilities\\get_dn_3.m" /* pathName */
};

static emlrtRSInfo tb_emlrtRSI = {
    385,                                                       /* lineNo */
    "get_dn_3",                                                /* fcnName */
    "G:\\My Drive\\AEROSP 740\\project\\utilities\\get_dn_3.m" /* pathName */
};

/* Function Definitions */
void get_dn_3(const emlrtStack *sp, const real_T q[7], const real_T o[21],
              real_T dn3[7])
{
  emlrtStack st;
  real_T a;
  real_T a_tmp;
  real_T b_a;
  real_T c_a;
  real_T t10;
  real_T t103;
  real_T t11;
  real_T t118;
  real_T t12;
  real_T t129;
  real_T t13;
  real_T t130;
  real_T t131;
  real_T t132;
  real_T t15;
  real_T t153;
  real_T t155;
  real_T t162;
  real_T t17;
  real_T t174;
  real_T t175;
  real_T t178;
  real_T t179;
  real_T t181;
  real_T t182;
  real_T t184;
  real_T t188;
  real_T t2;
  real_T t20;
  real_T t202;
  real_T t203;
  real_T t21;
  real_T t214;
  real_T t22;
  real_T t220;
  real_T t227;
  real_T t229_tmp;
  real_T t23;
  real_T t232;
  real_T t233;
  real_T t24;
  real_T t242;
  real_T t243;
  real_T t25;
  real_T t254;
  real_T t26;
  real_T t269;
  real_T t28;
  real_T t29;
  real_T t3;
  real_T t30;
  real_T t31;
  real_T t314;
  real_T t324;
  real_T t325;
  real_T t33;
  real_T t332;
  real_T t332_tmp;
  real_T t335;
  real_T t34;
  real_T t340;
  real_T t342;
  real_T t343;
  real_T t344;
  real_T t35;
  real_T t36;
  real_T t363;
  real_T t37;
  real_T t38;
  real_T t39;
  real_T t4;
  real_T t40;
  real_T t41;
  real_T t41_tmp;
  real_T t42;
  real_T t43;
  real_T t44;
  real_T t45;
  real_T t5;
  real_T t52;
  real_T t57;
  real_T t58;
  real_T t59;
  real_T t6;
  real_T t60;
  real_T t61;
  real_T t7;
  real_T t77;
  real_T t8;
  real_T t9;
  st.prev = sp;
  st.tls = sp->tls;
  /* GET_D_3 */
  /*     DN3 = GET_D_3(O1,O2,O3,Q1,Q2,Q3,Q4,Q5,Q6) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     08-Dec-2021 21:29:48 */
  t2 = muDoubleScalarCos(q[0]);
  t3 = muDoubleScalarCos(q[1]);
  t4 = muDoubleScalarCos(q[2]);
  t5 = muDoubleScalarCos(q[3]);
  t6 = muDoubleScalarCos(q[4]);
  t7 = muDoubleScalarCos(q[5]);
  t8 = muDoubleScalarSin(q[0]);
  t9 = muDoubleScalarSin(q[1]);
  t10 = muDoubleScalarSin(q[2]);
  t11 = muDoubleScalarSin(q[3]);
  t12 = muDoubleScalarSin(q[4]);
  t13 = muDoubleScalarSin(q[5]);
  t20 = o[2] * 50.0;
  t15 = t3 * t3;
  t17 = t9 * t9;
  t21 = t2 * t4;
  t22 = t3 * t5;
  t23 = t2 * t10;
  t24 = t4 * t8;
  t25 = t3 * t11;
  t26 = t8 * t10;
  t28 = t3 * 0.4;
  t37 = t8 * t9;
  t29 = t37 * t11;
  t31 = t9 * t10 * t12;
  t36 = t2 * t5 * t9;
  t38 = t4 * t5 * t9;
  t41_tmp = t2 * t9;
  t41 = t41_tmp * t11;
  t42 = t5 * t8 * t9;
  t45 = t4 * t9 * t11;
  t52 = t37 * 0.4;
  t10 *= t6 * t9;
  t181 = t10 * 0.0607;
  t30 = t11 * t26;
  t33 = t3 * t21;
  t34 = t3 * t23;
  t35 = t3 * t24;
  t37 = t5 * t23;
  t39 = t6 * t25;
  t40 = t3 * t26;
  t43 = t11 * t23;
  t44 = t5 * t26;
  t57 = t21 * t22;
  t58 = t21 * t25;
  t59 = t22 * t24;
  t60 = t6 * t38;
  t61 = t24 * t25;
  t77 = t42 * 0.4;
  t118 = t42 * 0.21;
  t129 = t24 * 0.0607;
  t130 = t25 * 0.0607;
  t162 = t29 * 0.0607;
  t179 = t41 * 0.0607;
  t363 = t12 * t38;
  t214 = t363 * -0.0607;
  t4 = t23 + t35;
  t103 = t24 + t34;
  t174 = t34 * 0.0607;
  t175 = t37 * 0.0607;
  t178 = t40 * 0.0607;
  t182 = t12 * t130;
  t202 = t57 * 0.0607;
  t203 = t59 * 0.0607;
  t227 = (t29 + t37) + t59;
  t232 = t22 * 0.21 + t45 * 0.21;
  t131 = t21 + -t40;
  t132 = t26 + -t33;
  t153 = t5 * t4;
  t155 = t12 * t103;
  t220 = t11 * (t23 * 0.4 + t24 * t28);
  t229_tmp = t11 * t4;
  t233 = (t41 + t57) + -t44;
  t242 = t6 * t227;
  t243 = t232 * t232;
  t254 = t7 * (t22 * 0.081 + t45 * 0.081);
  t4 = -o[2] + t28;
  t269 = (t4 + t232) + 0.34;
  a = (((t22 * 1900.0 + t12 * t25 * 607.0) + t45 * 1900.0) + -(t10 * 607.0)) +
      -(t363 * 607.0);
  t325 = (((t22 * 0.19 + t45 * 0.19) + t182) + -t181) + t214;
  t332_tmp = (t4 + t22 * 0.4) + t45 * 0.4;
  t332 = (((t332_tmp + t182) + -t181) + t214) + 0.34;
  t184 = t5 * t132;
  t188 = t12 * t131;
  t182 = t11 * (t23 * 0.21 + t35 * 0.21);
  t35 = t6 * t233;
  t23 = t6 * (t129 + t174);
  a_tmp = o[0] * t2;
  b_a = muDoubleScalarAbs(
      ((((-t20 + t15 * t20) + -(t15 * 17.0)) + a_tmp * t3 * t9 * 50.0) +
       o[1] * t3 * t8 * t9 * 50.0) +
      17.0);
  c_a = muDoubleScalarAbs((((o[0] * t15 * 50.0 + t2 * t3 * t9 * 17.0) +
                            o[2] * t2 * t3 * t9 * -50.0) +
                           o[0] * (t8 * t8) * t17 * 50.0) +
                          -(o[1] * t2 * t8 * t17 * 50.0));
  t5 = muDoubleScalarAbs((((o[1] * t15 * 50.0 + t3 * t8 * t9 * 17.0) +
                           o[2] * t3 * t8 * t9 * -50.0) +
                          o[1] * (t2 * t2) * t17 * 50.0) +
                         -(a_tmp * t8 * t17 * 50.0));
  t314 = a * a;
  t4 = t7 * t22;
  t10 = t7 * t45;
  t363 = t13 * t39;
  t214 = t13 * t31;
  t3 = t13 * t60;
  t324 = (((t4 * 0.045 + t10 * 0.045) + t363 * 0.045) + t214 * 0.045) +
         -(t3 * 0.045);
  t335 = (((((t332_tmp + t4 * 0.126) + t10 * 0.126) + t363 * 0.126) +
           t214 * 0.126) +
          -(t3 * 0.126)) +
         0.34;
  t4 = t6 * t13;
  t10 = t12 * t13;
  t340 = ((((((t7 * t42 * 0.045 + t10 * t21 * 0.045) + -(t7 * t43 * 0.045)) +
             t4 * t37 * 0.045) +
            t4 * t29 * 0.045) +
           -(t7 * t61 * 0.045)) +
          -(t10 * t40 * 0.045)) +
         t4 * t59 * 0.045;
  t342 = ((((((t7 * t36 * 0.045 + t7 * t30 * 0.045) + -(t10 * t24 * 0.045)) +
             t4 * t41 * 0.045) +
            -(t7 * t58 * 0.045)) +
           -(t10 * t34 * 0.045)) +
          -(t4 * t44 * 0.045)) +
         t4 * t57 * 0.045;
  t343 = ((((((t30 * 0.19 + t36 * 0.19) + -(t58 * 0.19)) + t6 * t129) +
            t6 * t174) +
           t12 * t179) +
          t12 * t44 * -0.0607) +
         t12 * t202;
  t344 =
      ((((((t42 * 0.19 + -(t43 * 0.19)) + -(t61 * 0.19)) + t6 * t21 * -0.0607) +
         t6 * t178) +
        t12 * t175) +
       t12 * t162) +
      t12 * t203;
  t214 = t6 * (t21 * 0.0607 + -t178);
  t10 = t13 * (t31 * 0.081 + t6 * (t25 + -t38) * 0.081);
  a_tmp = t118 - t182;
  t25 = a_tmp * a_tmp;
  a = t7 * (t22 + t45) + t13 * ((t31 + t39) + -t60);
  t60 = t11 * t132;
  t37 =
      ((t36 * 1900.0 + t6 * t103 * 607.0) + t60 * 1900.0) + t12 * t233 * 607.0;
  t39 = t36 * 0.21 + t11 * (t26 * 0.21 + -(t33 * 0.21));
  t28 = t7 * (t36 * 0.081 + t60 * 0.081);
  t132 = a * a;
  t4 = o[1] + -t52;
  t178 = t4 + (-t118 + t182);
  a = t7 * ((t30 + t36) + -t58) + -t13 * (t155 - t35);
  t182 = ((t42 * 1900.0 + -(t229_tmp * 1900.0)) + -(t6 * t131 * 607.0)) +
         t12 * t227 * 607.0;
  t21 = t37 * t37;
  t24 = ((t332_tmp + t254) + t10) + 0.34;
  t129 = ((t181 + t254) + -(t12 * (t130 + -(t38 * 0.0607)))) + t10;
  t363 = (t4 + -t77) + t220;
  t174 = (t363 + t214) + -(t12 * ((t162 + t175) + t203));
  t4 = -o[0] + t41_tmp * 0.4;
  t10 = (t4 + t36 * 0.4) + -t11 * (t33 * 0.4 - t26 * 0.4);
  t57 = (t10 + t23) + t12 * ((t179 + -(t44 * 0.0607)) + t202);
  t17 = t39 * t39;
  t40 = t4 + t39;
  t8 = t13 * (t188 * 0.081 + t6 * (t29 + t153) * 0.081);
  t37 = t13 * (t155 * 0.081 + t6 * (t41 - t184) * -0.081);
  t34 = a * a;
  t59 = t182 * t182;
  t2 = t129 * t129;
  t9 = (t10 + t7 * ((t30 * 0.126 + t36 * 0.126) + -(t58 * 0.126))) +
       -t13 * (t155 * 0.126 - t35 * 0.126);
  t4 = (b_a * b_a + c_a * c_a) + t5 * t5;
  st.site = &lb_emlrtRSI;
  if (t4 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &h_emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t4 = muDoubleScalarSqrt(t4);
  a = t7 * ((t43 + t61) + -t42) + -(t13 * (t188 + t242));
  t15 = t4 / 50.0;
  t4 = t7 * (t42 * 0.081 - t229_tmp * 0.081);
  t60 = ((t214 - t12 * (t162 + t153 * 0.0607)) + t8) + t4;
  t5 = t60 * t60;
  t3 = ((t23 - t28) + t37) + t12 * (t179 - t184 * 0.0607);
  t182 = t3 * t3;
  t20 = a * a;
  t23 = 1.0 / ((t243 + t17) + t25);
  t35 = (t363 + t7 * ((t43 * 0.126 + -(t42 * 0.126)) + t61 * 0.126)) +
        -(t13 * (t188 * 0.126 + t242 * 0.126));
  t10 = (t10 + t28) + -t37;
  t28 = 1.0 / ((t314 + t21) + t59);
  t363 = 1.0 / ((t2 + t5) + t182);
  t214 = 1.0 / ((t132 + t34) + t20);
  t37 = ((((-o[1] + t52) + t77) - t220) + t8) + t4;
  a = muDoubleScalarAbs((t24 * (t2 * t363 - 1.0) - t129 * t10 * t363 * t3) +
                        t129 * t363 * t60 * t37);
  t4 = t24 * t129 * t363;
  b_a = muDoubleScalarAbs((-(t5 * t363 - 1.0) * t37 - t4 * t60) +
                          t10 * t363 * t60 * t3);
  c_a = muDoubleScalarAbs((t10 * (t182 * t363 - 1.0) - t4 * t3) -
                          t363 * t60 * t3 * t37);
  t5 = muDoubleScalarAbs(o[0]);
  t37 = muDoubleScalarAbs(o[1]);
  t182 =
      muDoubleScalarAbs((t269 * (t243 * t23 - 1.0) + t232 * t39 * t40 * t23) -
                        t232 * t178 * t23 * a_tmp);
  t60 = t232 * t269;
  t4 = muDoubleScalarAbs((t40 * (t17 * t23 - 1.0) + t60 * t39 * t23) -
                         t39 * t178 * t23 * a_tmp);
  t10 = muDoubleScalarAbs((t178 * (t25 * t23 - 1.0) - t60 * t23 * a_tmp) -
                          t39 * t40 * t23 * a_tmp);
  t3 = t5 * t5 + t37 * t37;
  st.site = &rb_emlrtRSI;
  if (t3 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &h_emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t3 = muDoubleScalarSqrt(t3);
  t363 = (t182 * t182 + t4 * t4) + t10 * t10;
  st.site = &rb_emlrtRSI;
  if (t363 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &h_emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t363 = muDoubleScalarSqrt(t363);
  t5 = muDoubleScalarAbs(
      (t332 * (t314 * t28 - 1.0) + t325 * t343 * t57 * t28 * 1.0E+8) -
      t325 * t344 * t174 * t28 * 1.0E+8);
  a_tmp = t325 * t332;
  t60 = t343 * t344;
  t37 = muDoubleScalarAbs(
      (t57 * (t21 * t28 - 1.0) + a_tmp * t343 * t28 * 1.0E+8) -
      t60 * t174 * t28 * 1.0E+8);
  t182 = muDoubleScalarAbs(
      (-t174 * (t59 * t28 - 1.0) + a_tmp * t344 * t28 * 1.0E+8) +
      t60 * t57 * t28 * 1.0E+8);
  t10 = (t5 * t5 + t37 * t37) + t182 * t182;
  st.site = &sb_emlrtRSI;
  if (t10 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &h_emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t10 = muDoubleScalarSqrt(t10);
  t37 = (a * a + b_a * b_a) + c_a * c_a;
  st.site = &sb_emlrtRSI;
  if (t37 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &h_emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t37 = muDoubleScalarSqrt(t37);
  a = muDoubleScalarAbs((t335 * (t132 * t214 - 1.0) -
                         t324 * t340 * t35 * t214 * 493.82716049382719) +
                        t324 * t342 * t9 * t214 * 493.82716049382719);
  a_tmp = t324 * t335;
  t60 = t340 * t342;
  b_a = muDoubleScalarAbs(
      (t9 * (t34 * t214 - 1.0) + a_tmp * t342 * t214 * 493.82716049382719) -
      t60 * t35 * t214 * 493.82716049382719);
  c_a = muDoubleScalarAbs(
      (-t35 * (t20 * t214 - 1.0) + a_tmp * t340 * t214 * 493.82716049382719) +
      t60 * t9 * t214 * 493.82716049382719);
  t4 = (a * a + b_a * b_a) + c_a * c_a;
  st.site = &tb_emlrtRSI;
  if (t4 < 0.0) {
    emlrtErrorWithMessageIdR2018a(
        &st, &h_emlrtRTEI, "Coder:toolbox:ElFunDomainError",
        "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
  }
  t4 = muDoubleScalarSqrt(t4);
  dn3[0] = t3;
  dn3[1] = t15;
  dn3[2] = t15;
  dn3[3] = t363;
  dn3[4] = t10;
  dn3[5] = t37;
  dn3[6] = t4;
}

/* End of code generation (get_dn_3.c) */
